# Generated by Django 5.0.6 on 2024-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='genders',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=100),
        ),
    ]
