# Generated by Django 5.0.6 on 2024-06-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_resumedata_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='my_file',
            field=models.FileField(blank=True, upload_to='Doc'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_city',
            field=models.CharField(choices=[('PUNE', 'PUNE'), ('MUMBAI', 'MUMBAI'), ('BANGLORE', 'BANGLORE'), ('THANE', 'THANE'), ('VASHI', 'VASHI'), ('NAVI MUMBAI', 'NAVI MUMBAI'), ('KALYAN', 'KALYAN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
    ]
