# Generated by Django 5.0.6 on 2024-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_resumedata_my_file_alter_resumedata_job_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='genders',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100),
        ),
    ]
