# Generated by Django 5.0 on 2024-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_resumedata_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='job_city',
            field=models.CharField(choices=[('PUNE', 'PUNE'), ('MUMBAI', 'MUMBAI'), ('BANGLORE', 'BANGLORE'), ('THANE', 'THANE'), ('VASHI', 'VASHI'), ('NAVI MUMBAI', 'NAVI MUMBAI'), ('KALYAN', 'KALYAN')], max_length=200),
        ),
    ]
