# Generated by Django 5.0 on 2024-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_resumedata_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='genders',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_city',
            field=models.CharField(max_length=200),
        ),
    ]
