# Generated by Django 4.2.9 on 2024-06-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_resumedata_my_file_alter_resumedata_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedata",
            name="skills",
            field=models.CharField(default="html", max_length=200),
            preserve_default=False,
        ),
    ]
